// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AcceptDeclineBookingController from "./accept_decline_booking_controller"
application.register("accept-decline-booking", AcceptDeclineBookingController)

import AnimatedStarsJsController from "./animated_stars_js_controller"
application.register("animated-stars-js", AnimatedStarsJsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)


